import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
	const set = {
		labels: {
		},
		keywords: {
		},
	}

	await Promise.all
	([['3GPP','3gpp'],
	['5G','5g,5g lte'],
	['AI','ai,artificial intelligence'],
	['AKS','aks,azure kubernetes,azurekubernetes'],
	['API','api,apis,application programming interface,application programming interfaces'],
	['AUTOSAR','auto sar,auto-sar,autosar'],
	['AWS','aws'],
	['AWS CDK','aws cdk,aws-cdk,awscdk'],
	['AWS CodePipeline','aws codepipeline,aws-codepipeline,code pipeline,code-pipeline,codepipeline'],
	['Abacus','abacus'],
	['Adobe','adobe'],
	['Adobe AEM','adobe aem,adobe-aem,adobeaem'],
	['Adobe Illustrator','adobe illustrator'],
	['Advanced Business Application Programming (ABAP)','abap,advanced business application programming'],
	['Agile','agile,scrum,sprint'],
	['AirFlow','airflow'],
	['Ajax','ajax'],
	['Amazon','amazon'],
	['Android','android'],
	['Android Auto','android auto'],
	['Android Studio','android studio'],
	['Android TV','android tv'],
	['Android X','android x'],
	['Angular','angular,angular-js,angularjs'],
	['Ansible','ansible'],
	['AnyPoint','anypoint'],
	['Apache','apache'],
	['Apache Ignite','apache ignite,apache-ignite,apacheignite'],
	['Apex','apex'],
	['App Store','app store,apple app store'],
	['Appium','appium'],
	['Archer','archer'],
	['Asana','asana'],
	['Assembly','assembly'],
	['Astro','astro'],
	['Atlassian Confluence','atlassian confluence,confluence'],
	['Audio','audio,sfx,sound'],
	['Aura','aura'],
	['AutoCAD','auto cad,auto-cad,autocad'],
	['Autodesk','auto desk,auto-desk,autodesk'],
	['Azure','azure'],
	['Azure AD B2C','azure ad b2c,azure ad-b2c,azure adb2c'],
	['Azure Blob Storage','azure blob storage,blob storage,blob-storage,blobstorage'],
	['Azure Boards','azure boards,azure-boards,azureboards'],
	['Azure Data Factory','azure data factory,data factory'],
	['Azure Databricks','azure databricks,data bricks,data-bricks,databricks'],
	['Azure IDP','azure idp'],
	['Azure Managed Application Services','azure managed application services'],
	['Azure SQL Server','azure sql,azure-sql,azuresql'],
	['Azure Synapse Analytics','azure synapse,azure-synapse,azuresynapse'],
	['BEM','bem'],
	['BI Publisher','bi publisher,bi-publisher,bipublisher'],
	['Babel','babel'],
	['BadgerDB','badgerdb'],
	['Bash','bash'],
	['Batch','batch'],
	['Behat','behat'],
	['BigQuery','bigquery'],
	['Birst','birst'],
	['Bitbucket','bitbucket'],
	['Blockchain','blockchain'],
	['Bluetooth/BLE','ble,bluetooth'],
	['Bootstrap','bootstrap'],
	['Brightscript','brightscript,brightscripts'],
	['C','c'],
	['CI/CD','ci cd,ci-cd,ci/cd,cicd,continous delivery,continous integration,continuous deliveries,continuous delivery,continuous integration,continuous integrations,continuous-delivery,continuous-integration,continuousdelivery,continuousintegration'],
	['CRM','crm,customer relations management,customer relationship management,customer relationships management'],
	['CSS','css,css3'],
	['CSS3','css3'],
	['CVI','cvi'],
	['CaaS','caas'],
	['Canva','canva'],
	['Capacitor','capacitor'],
	['CarPlay','carplay'],
	['Cassandra','cassandra'],
	['Celery','celery'],
	['Cerner Command Language','ccl,cerner ccl,cerner command language,cerner-ccl,cernerccl'],
	['Cerner Millennium','cerner millennium,cerner-millennium,cernermillennium'],
	['Chai','chai'],
	['ChatGPT','chat gpt,chat-gpt,chatgpt'],
	['CircleCI','circle ci,circle-ci,circleci'],
	['Civil 3D','civil 3d,civil-3d,civil3d'],
	['ClearCase','clearcase'],
	['ClearQuest','clearquest'],
	['Cloud','cloud'],
	['CloudFront','cloud front,cloud-front,cloudfront'],
	['Cloudwatch','cloudwatch'],
	['Code Coverage','code coverage'],
	['Codecommit','codecommit'],
	['Compose','compose'],
	['Computer Vision','computer vision,computer-vision,computervision,open cv,open-cv,opencv'],
	['Computer-aided design (CAD)','cad,computer-aided design'],
	['Configuration Management','configuration management'],
	['Containerization','container,containerization,containerized,containers'],
	['Context API','context api'],
	['Coroutines','coroutine,coroutines'],
	['Cosmos DB','cosmos db,cosmos-db,cosmosdb'],
	['CouchDB','couch db,couch-db,couchdb'],
	['Cucumber','cucumber'],
	['Cypress','cypress'],
	['DASH','dash'],
	['DB2','db 2,db-2,db2'],
	['DOM','dom'],
	['DRY','dry'],
	['Dart','dart'],
	['Data Analysis','data analysis,data analysis software,data analytics'],
	['Data Integration','data integration'],
	['Data Lifecycle Management','data life,data lifecycle'],
	['Data Management','data management'],
	['Data Pipelines','data pipe line,data pipe lines,data pipe-line,data pipe-lines,data pipeline,data pipelines'],
	['Data Science','data science,data sciences,data scientist,data scientists,data-science,data-sciences,data-scientist,data-scientists'],
	['Data Storage','data storage,data store,data stores,datastore,datastores'],
	['Data Structures','data structures,datastructures'],
	['Data Warehousing','data warehousing'],
	['DataViews','data views,data-views,dataviews'],
	['Database Management Systems (DBMS)','data base,data bases,database,database management systems,databases,dbms'],
	['Dataloader','dataloader'],
	['Dataverse','data verse,data-verse,dataverse'],
	['Debugging','debug,debugger,debuggers,debugging'],
	['Deep Learning','deep learning,deep-learning,deeplearning'],
	['Delphi','delphi'],
	['Design Patterns','design patterns'],
	['Desktop Applications','desktop applications'],
	['DevExpress','devexpress'],
	['DevOps','dev ops,dev-ops,devops'],
	['Django','django,django rest,drf'],
	['Django Rest Framework','django rest,django rest framework,drf'],
	['Docker','docker'],
	['Docusign','docusign'],
	['Dojo','dojo'],
	['Dynamics 365','dynamics 365,dynamics-365,dynamics365'],
	['DynamoDB','dynamo,dynamodb'],
	['Dynatrace','dyna trace,dyna-trace,dynatrace'],
	['EC-Council','ec council,ec-council,eccouncil'],
	['EC2','ec 2,ec-2,ec2'],
	['ECMAScript','ecmascript'],
	['EKS','eks'],
	['ELT','elt'],
	['ERP','erp'],
	['ETL','etl'],
	['Eclipse','eclipse'],
	['Elastic Search','elastic search,elasticsearch'],
	['Enterprise Application Integration','eai,enterprise application integration'],
	['Enterprise Data Lake','enterprise data lake'],
	['Entity Framework','entity framework'],
	['Erlang','erlang'],
	['Espresso','espresso'],
	['Experience Cloud','experience cloud'],
	['Express','express'],
	['ExtJS','extjs'],
	['FTP','ftp,ftps,sftp'],
	['Facebook','facebook'],
	['FastAPI','fastapi'],
	['Fiddler','fiddler'],
	['Filestore','filestore'],
	['Firebase','fire base,fire-base,firebase'],
	['Firestore','firestore'],
	['Firewall','firewall,firewalls'],
	['Flask','flask'],
	['Flow Builder','flow builder,flowbuilder'],
	['Flutter','flutter'],
	['FormStack','formstack'],
	['Foxpro','foxpro'],
	['FreeRTOS','freertos'],
	['GCC','gcc'],
	['GCDocs','gcdocs'],
	['GLUE','glue'],
	['GOSU','gosu'],
	['GPT','gpt'],
	['GenAI','gen ai,gen-ai,genai'],
	['Geospatial Systems Technology','geospatial systems,geospatial systems technology'],
	['Gherkin','gherkin'],
	['Git','git'],
	['GitHub','github'],
	['GitHub Actions','github action,github actions,github-action,github-actions,githubaction,githubactions'],
	['GitOps','gitops'],
	['Go','go'],
	['Google Analytics','google analytics,google-analytics,googleanalytics'],
	['Google Cloud','google cloud'],
	['Google Cloud Platform (GCP)','gcp,google cloud platform'],
	['Google Gemini','gemini,google gemini,google-gemini,googlegemini'],
	['Google Kubernetes Engine (GKE)','gke,google kubernetes engine'],
	['Google Play Store','google play,google play store,play store'],
	['Gradle','gradle'],
	['Grafana','grafana,graphana'],
	['GraphQL','graphql'],
	['Graphics','graphics'],
	['GreenHills','greenhills'],
	['Gupta','gupta'],
	['HLS','hls'],
	['HTML','html,html5'],
	['HTML5','html5'],
	['Hadoop','hadoop'],
	['Hibernate','hibernate,hibernate 4,hibernate-4,hibernate4'],
	['Hibernate4','hibernate 4,hibernate-4,hibernate4'],
	['HyperV','hyper v,hyper-v,hyperv'],
	['IOT','iot'],
	['IaaS','iaas'],
	['IndexedDB','indexed db,indexed-db,indexeddb'],
	['Infor','infor'],
	['Informatica','informatica'],
	['Informix 4GL','informix 4gl'],
	['IntelliJ','intellij'],
	['Ionic','ionic'],
	['J2EE','j2 ee,j2-ee,j2ee,java ee,java-ee,javaee'],
	['JAX-RS','jax rs,jax-rs,jaxrs'],
	['JEE','jee'],
	['JIRA','jira'],
	['JMC','jmc'],
	['JMS','jms'],
	['JPA','jpa'],
	['JSON','java script object notation,javascript object notation,json'],
	['JSP','jsp'],
	['JTAG','jtag'],
	['JUnit','junit'],
	['JVM','jvm'],
	['JWT','json web token,jwt'],
	['Java','java'],
	['Javascript','java script,java scripts,java-script,java-scripts,javascript,javascripts'],
	['Jconsole','j console,j-console,jconsole'],
	['Jelly','jelly'],
	['Jenkins','jenkins'],
	['Jetpack','jetpack'],
	['Jetson','jetson'],
	['K8s','k8,k8s'],
	['KANBAN','kanban'],
	['KPI','kpi,kpis'],
	['KVM','kvm'],
	['Kafka','kafka'],
	['Katalon','katalon'],
	['Keras','keras'],
	['Kibana','kibana'],
	['Kinesis','kinesis'],
	['Kotlin','kotlin'],
	['Kotlin Flow','kotlin flow'],
	['Kubernetes','kubernetes'],
	['LAMP','lamp'],
	['LWC','lwc'],
	['LWR','lwr'],
	['Lab View','lab view,lab-view,labview'],
	['Lambda','lambda'],
	['LangChain','langchain'],
	['Laravel','laravel'],
	['Large Language Models (LLMs)','large language model,large language models,llm,llm ops,llm-ops,llmops,llms'],
	['LiDAR','lidar,lidars'],
	['Licensing and Control System (LCS)','lcs,licensing and control system,licensing and control systems'],
	['Lightning','lightning'],
	['Lightning Design System','lightning design,lightning design system'],
	['Lightning Web Components','lightning web component,lightning web components'],
	['Linux','linux'],
	['Load Balancers','load balancers'],
	['Logic Apps','logic apps,logic-apps,logicapps'],
	['Lora','lora'],
	['Lucene','lucene'],
	['MACH digital architecture','mach,mach digital architecture'],
	['MATLAB','matlab'],
	['MCU','mcu'],
	['MFC','mfc'],
	['MS Active Directory','microsoft active directory,microsoft active-directory,microsoft ad,microsoft-ad,ms active directory,ms ad,ms-ad,msad'],
	['MS IIS','iis web,iis webserver,iis-server,iis-web,iis-webserver,iiswebserver,microsoft iis,microsoft-iis,microsoftiis,ms iis,ms-iis,msiis'],
	['MSSQL','microsoft sql,ms sql,mssql'],
	['MVC','mvc'],
	['MVC4','mvc 4,mvc-4,mvc4'],
	['MVI','mvi'],
	['MVVM','mvvm'],
	['Mac OSX','mac,mac os,mac osx,macintosh,macos,macosx'],
	['Machine Learning','machine learning,ml,mlops'],
	['Mail Chimp','mail chimp,mailchimp'],
	['Maven','maven'],
	['Memcached','memcached'],
	['Message Queue','message queue,message queues,mq,rabbitmq'],
	['Meteor','meteor'],
	['Microfocus','micro focus,micro-focus,microfocus'],
	['Microfocus ALM','microfocus alm'],
	['Microfocus Load Runner','microfocus load runner,microfocus load-runner,microfocus loadrunner'],
	['Microfocus Octante','microfocus octante'],
	['Microservices','micro services,micro-services,microservices'],
	['Microsoft Access','access,microsoft access,ms access,msaccess'],
	['Microsoft Excel','microsoft excel,ms excel,msexcel'],
	['Microsoft Fabric','fabric,microsoft fabric,ms fabric,msfabric'],
	['Microsoft Office','microsoft office,ms office,msoffice'],
	['Microsoft Office 365','o365,office 365'],
	['Microsoft Outlook','microsoft outlook,ms outlook,msoutlook,outlook'],
	['Microsoft Powerpoint','microsoft powerpoint,ms powerpoint,mspowerpoint,power point,powerpoint'],
	['Microsoft Project','microsoft project,ms project,msproject'],
	['Microsoft Word','microsoft word,ms word,msword'],
	['Mobile','mobile'],
	['Mocha','mocha'],
	['Mockito','mockito'],
	['Moleculer','moleculer'],
	['MongoDB','mongo,mongo db,mongo-db,mongodb'],
	['MuleSoft','mulesoft'],
	['Multi-threading','async,asynchronous,concurrency,concurrent,multi thread,multi threaded,multi threading,multi threads,multi-thread,multi-threaded,multi-threading,multi-threads,multithread,multithreaded,multithreading,multithreads,parallel computing,parallel processing,parallelization,re-entrancy,re-entrant,reentrancy,reentrant,synchronization,threading,threads'],
	['Multimedia','multi media,multi-media,multimedia'],
	['MySQL','mysql'],
	['NATS','nats'],
	['NLP','natural language processing,natural language processor,natural-language-processing,natural-language-processor,nlp'],
	['NPM','npm'],
	['NestJS','nestjs'],
	['Netconf','netconf'],
	['Networks','network,networking,networks,protocol,protocols'],
	['NextJS','next js,next-js,nextjs'],
	['Nexus','nexus'],
	['Nifi','nifi'],
	['Nightwatch','night watch,night-watch,nightwatch'],
	['NoSQL','nosql'],
	['Node.js','node,node js,node-js,nodejs'],
	['Nordic','nordic'],
	['OAuth','oauth,oauth-2,oauth2'],
	['OCR','ocr,optical character recognition'],
	['OData Standard','odata standard,odata standards'],
	['OPA','opa'],
	['ORM','object database,object relation,object relational,object relations,object relationships,orm,relational object'],
	['OSS','oss'],
	['OTA','ota'],
	['Object-oriented Programming (OOP)','object oriented,object-oriented,object-oriented programming,oo,oop'],
	['Objective C','objective c'],
	['Okta','okta'],
	['Open API','open api,open apis,open-api,open-apis,openapi,openapis'],
	['Open Search','open search,opensearch'],
	['Open Source','open source,open-source'],
	['OpenAI','open ai,open ais,open-ai,open-ais,openai,openais'],
	['OpenCL','opencl'],
	['OpenCV','opencv'],
	['OpenGL','opengl'],
	['OpenID Connect','openid connect'],
	['OpenShift','openshift'],
	['OpenTelemetry','open telemetry,open-telemetry,opentelemetry'],
	['Operating Systems','operating system,operating systems,os'],
	['Oracle','oracle'],
	['Oracle Application Frame','oaf,oracle application frame,oracle application frames'],
	['Oracle Business Intelligence Enterprise Edition','obiee,oracle business intelligence enterprise edition'],
	['Oracle EBS','oracle ebs,oracle-ebs'],
	['Oracle Financials','oracle financials'],
	['Oracle Forms','oracle forms'],
	['Oracle Payments','oracle payment,oracle payments,oracle-payment,oracle-payments,oraclepayment,oraclepayments'],
	['Oracle Reports','oracle report,oracle reports,oracle-report,oracle-reports,oraclereport,oraclereports'],
	['Oracle eBusiness Suite','oracle ebusiness suite'],
	['Orchestration','orchestrate,orchestration,orchestrator'],
	['Orin','orin'],
	['PCIe','pcie'],
	['PHP','php'],
	['PHPUnit','php unit,php-unit,phpunit'],
	['PL/SQL','pl sql,pl-sql,pl/sql,plsql'],
	['PaaS','paas'],
	['Parquet','parquet'],
	['Perforce','perforce'],
	['Perl','perl'],
	['Playwright','playwright'],
	['Polarion','polarion'],
	['PostgreSQL','postgres,postgresql'],
	['Postman','postman'],
	['Power Automate','power automate,power automates,power-automate,power-automates,powerautomate,powerautomates'],
	['PowerApps','power apps,power-apps,powerapps'],
	['PowerBI','power bi,power-bi,powerbi'],
	['PowerBuilder','powerbuilder'],
	['Powershell','power shell,power shells,power-shell,power-shells,powershell,powershells'],
	['Progressive Web Apps (PWA)','progressive web app,progressive web apps,progressive web-app,progressive web-apps,progressive webapp,progressive webapps,pwa'],
	['Project Management','project management'],
	['ProjectWise','project wise,project-wise,projectwise'],
	['Prometheus','prometheus'],
	['Pub/Sub','pub/sub'],
	['PySpark','pyspark'],
	['PyTorch','pytorch'],
	['Pyramid','pyramid'],
	['Python','python'],
	['QNX','qnx'],
	['QT','qt'],
	['Qlik','qlik'],
	['RBMS','rbms'],
	['REST','rest,rest-api,rest-apis,restapi,restapis,restful'],
	['RTOS','freertos,rtos,zephyr'],
	['RTP','rtp'],
	['RabbitMQ','rabbitmq'],
	['Rackspace','rackspace'],
	['Rapid Application Development','rad,rapid application development'],
	['React','react,react js,react-js,reactjs'],
	['ReadyAPI','ready api,ready-api,readyapi'],
	['Redis','redis'],
	['Redux','redux'],
	['Retrofit','retrofit'],
	['Ross Web Platform (RWP)','ross web platform,rwp'],
	['Ruby','ruby,ruby on rails'],
	['Ruby on Rails','ruby on rails'],
	['RxJs','rx js,rxjs'],
	['S3','amazon simple storage service,s3'],
	['SAP','sap'],
	['SAS','sas'],
	['SASS','sass'],
	['SCSS','scss'],
	['SFTP','sftp'],
	['SIEM','siem'],
	['SNMP','snmp'],
	['SNS','sns'],
	['SOAP','soap'],
	['SPC','spc'],
	['SQL','sql'],
	['SQL Server Integration Services','sql server integration services,ssis'],
	['SQLAlchemy','sql alchemy,sql-alchemy,sqlalchemy'],
	['SQLite','lite sql,lite-sql,sql lite,sql lite3,sql-lite,sql-lite3,sqlite,sqlite3'],
	['SQS','sqs'],
	['SSH','ssh'],
	['SVN','svn'],
	['SaaS','saas,software as a service'],
	['Sailpoint','sail point,sail-point,sailpoint'],
	['Salesforce','salesforce'],
	['Scala','scala'],
	['ScalaTest','scala test,scala-test,scalatest'],
	['Scripting','script,scripting,scripts'],
	['Selenium','selenium'],
	['Serverless','server less,server-less,serverless'],
	['SharePoint','sharepoint'],
	['Siebel','siebel'],
	['Siebel Approval Manager','siebel approval manager,siebel approval-manager,siebel approvalmanager'],
	['Siebel EIM','siebel eim,siebel-eim,siebeleim'],
	['Siebel IP18','siebel ip18,siebel-ip18,siebelip18'],
	['Siebel Open UI','siebel open ui,siebel open-ui,siebel openui'],
	['Single Page Applications (SPA)','single page application,single page applications,spa'],
	['Site Reliability Engineering (SRE)','site reliability engineering,sre'],
	['Skaffold','skaffold'],
	['Slack','slack'],
	['Software Development Lifecycle (SDLC)','life cycle software,life cycle software development,life-cycle software,life-cycle software development,lifecycle software,lifecycle software development,sdlc,software development life cycle,software development life-cycle,software development lifecycle,software life cycle,software life-cycle,software lifecycle'],
	['Solace','solace'],
	['Solidity','solidity'],
	['Solution Design Document','sdd,solution design document,solution design documents'],
	['Spark','spark'],
	['Spinnaker','spinnaker'],
	['Spring','spring,springboot'],
	['Svelte','svelte'],
	['Swagger','swagger'],
	['Swarm','swarm'],
	['Swift','swift'],
	['Syteline','syteline'],
	['T-SQL','t sql,t-sql,t/sql,tsql'],
	['TCP/IP','tcp,tcp ip,tcp-ip,tcp/ip,tcpip'],
	['TDD','tdd,test driven,test-driven'],
	['TERADATA','teradata'],
	['TFS','tfs'],
	['TM Forum','tm forum'],
	['TSO','tso'],
	['Tableau','tableau'],
	['Talend','talend'],
	['Teamcity','teamcity'],
	['TensorFlow','tensorflow'],
	['Terraform','terraform'],
	['TestNG','testng'],
	['TestStand','test stand,test-stand,teststand'],
	['Testing','test,tester,testing,tests'],
	['Typescript','typescript,typescripts'],
	['UDP','udp,udp ip,udp-ip,udp/ip,udpip'],
	['UI','ui,uis,user interface,user interfaces'],
	['UML','uml'],
	['UX','user experience,user experiences,user-experience,user-experiences,userexperience,userexperiences,ux'],
	['Unified Functional Testing','uft,unified functional testing'],
	['Unit Testing','unit test,unit tester,unit testing,unit tests,unit-test,unit-tester,unit-testing,unit-tests,unittest,unittester,unittesting,unittests'],
	['Unix','unix'],
	['VMWare','vmware'],
	['VXworks','vxworks'],
	['Vbscript','vb script,vb-script,vbscript'],
	['Visio','visio'],
	['Visual Basic','vb,vb script,vb-script,vba,vbscript,visual basic'],
	['Visual Fox Pro','visual fox pro,visual fox-pro,visual foxpro'],
	['Visual Studio','visual studio,visual studio code,vs code,vscode'],
	['Visualforce','visualforce'],
	['Vue.js','vue,vue js,vue-js,vuejs'],
	['Vuetify','vuetify'],
	['W3C','w3c'],
	['WAI-ARIA','aria,wai aria,wai-aria,waiaria'],
	['WAVE','wave'],
	['WCAG','wcag,web content accessibility,web content accessibility guidelines'],
	['WebRTC','webrtc'],
	['Webpack','webpack'],
	['Websocket','websocket'],
	['WiFi','wi-fi,wifi,wireless'],
	['Win32','win32'],
	['Windows','windows'],
	['Windows Presentation Foundation','windows presentation foundation,wpf'],
	['Windows Server','windows server'],
	['WordPress','wordpress'],
	['Workbench','workbench'],
	['XCode','xcode'],
	['XML','dtd,xml,xsd,xsl'],
	['XPath','xpath'],
	['XRM Toolbox','xrm tool box,xrm tool-box,xrm toolbox'],
	['XSLT','xslt'],
	['Xamarin','xamarin'],
	['Xavier','xavier'],
	['Xilinx DSPs','xilinx dsp,xilinx dsps,xilinx-dsp,xilinx-dsps,xilinxdsp,xilinxdsps'],
	['YAML','yaml'],
	['YANG','yang'],
	['Yocto','yocto'],
	['Zephyr','zephyr'],
	['Zigbee','zigbee'],
	['ag-Grid','ag-grid'],
	['amCharts','amcharts'],
	['conan','conan'],
	['gRPC','grpc'],
	['iOS','ios'],
	['jQuery','jquery'],
	['jvisualvm','j visual vm,j visual-vm,j visualvm,j-visualvm,jvisualvm'],
	['myt','myt'],
	['scikit-learn','scikit-learn']]
	.map(([ label, keywords ]) => {
		const keywordsList = keywords.split(',')

		set.labels[label] = keywordsList

		keywordsList.forEach((keyword) => (
			set.keywords[keyword] = 0
		))
	}))

	await prisma.keywordsOnLabels.deleteMany()
	await prisma.keyword.deleteMany()
	await prisma.label.deleteMany()
	await prisma.color.deleteMany()

	const keywords = await prisma.keyword.createManyAndReturn({
		data: Object.keys(set.keywords).map((keyword) => ({ keyword })),
	})

	keywords.forEach(({ id, keyword }) => (
		set.keywords[keyword] = id
	))

	const { id } = await prisma.color.create({
		data: {
			color: 'ff0000',
		},
		select: {
			id: true,
		},
	})

	const labels = await prisma.label.createManyAndReturn({
		data: Object.keys(set.labels).map((label) => ({
			label: label,
			colorId: id,
		})),
	})

	await prisma.keywordsOnLabels.createMany({
		data: labels.map(({ id, label }) => (
			set.labels[label].map((keyword) => ({
				labelId: id,
				keywordId: set.keywords[keyword],
			}))
		)).reduce((keywordsOnLabels, newList) => [
			...keywordsOnLabels,
			...newList,
		], []),
	})
}

main()
	.then(async () => {
		await prisma.$disconnect()
	})
	.catch(async (e) => {
		console.error(e)
		await prisma.$disconnect()
		process.exit(1)
	})
